#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr

bspc monitor -d ¹ ² ³ 切⁴ ﬐⁵ ⁶ ⁷ ﱘ⁸ ⁹

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#5e81ac"
bspc config normal_border_color "#4c566a"
bspc config focus_follows_pointer true
bspc config top_padding +30

bspc rule -a firefox desktop='^3'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a QQ desktop='^5'
bspc rule -a Virt-manager desktop='^6'
bspc rule -a Gimp desktop='^8'
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Plank manage=off border=off locked=on focus=off follow=off layer=above

bspc subscribe node_add | while read -r _; do
   xdo raise -N Plank
done
