-- Generated by nwg-displays on 2026-06-18 at 13:01:12. Do not edit manually.

hl.monitor({
    output = "desc:BOE NS145F8M-N62 0x0000006E",
    mode = "3072x1920@120.0",
    position = "4800x1067",
    scale = 2.0
})
hl.monitor({
    output = "desc:Invalid Vendor Codename - RTK 0x0000 0x19201200",
    mode = "1920x1200@60.0",
    position = "2880x827",
    scale = 1.0
})
