-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(81a1c1)",
			inactive_border = "rgb(d8dee9)",
		},
	},
	group = {
		col = {
			border_active = "rgb(81a1c1)",
			border_inactive = "rgb(d8dee9)",
			border_locked_active = "rgb(bf616a)",
			border_locked_inactive = "rgb(d8dee9)",
		},
		groupbar = {
			col = {
				active = "rgb(81a1c1)",
				inactive = "rgb(d8dee9)",
				locked_active = "rgb(bf616a)",
				locked_inactive = "rgb(d8dee9)",
			},
		},
	},
})
